import {flowExplorerMarkup,mountFlowExplorer,disposeFlowExplorer} from './flow-explorer.js';
const $=id=>document.getElementById(id),state={project:null,program:null,block:null,calls:[],call:null};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(route,args={})=>{if(!['project','health','import-status'].includes(route)&&state.project?.snapshotId)args={projectId:state.project.projectId,snapshotId:state.project.snapshotId,...args};const r=await fetch(`/api/${route}?${new URLSearchParams(args)}`);const data=await r.json();if(!r.ok)throw Error(data.error);return data;};
const safe=fn=>async(...args)=>{try{$('error').hidden=true;await fn(...args);}catch(e){$('error').textContent=e.message;$('error').hidden=false;}};
const statusLabel=s=>({parsed:'已解析',protected:'有保护',failed:'失败','metadata-only':'仅目录',unresolved:'未解析'}[s]??s);
const table=(heads,rows)=>`<div class="table-scroll"><table><thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
const tab=name=>{document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==name);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));

function renderBlocks(){const q=$('block-search').value.toLowerCase();const items=state.project.blocks.filter(b=>b.programId===state.program&&[b.name,b.symbol,b.description].join(' ').toLowerCase().includes(q));$('block-count').textContent=`${items.length} 条块记录`;$('blocks').innerHTML=items.map(b=>`<button class="block-item ${b.id===state.block?'selected':''}" data-block="${esc(b.id)}"><span><strong>${esc(b.name)}</strong><small>${esc(b.symbol||b.description||b.type)}</small></span><span class="badge ${b.status==='parsed'?'':'warn'}">${statusLabel(b.status)}</span></button>`).join('');$('blocks').querySelectorAll('button').forEach(b=>b.onclick=safe(()=>selectBlock(b.dataset.block)));}
async function selectProgram(){disposeFlowExplorer();state.program=$('program').value;$('point-results').innerHTML='<p class="empty">输入点位后开始追踪。</p>';const own=state.project.blocks.filter(b=>b.programId===state.program);if(own.length)await selectBlock((own.find(b=>b.name==='FC156')??own[0]).id);await searchSymbols();}
async function selectBlock(id){state.block=id;state.call=null;$('flow').innerHTML='';$('flow-summary').textContent='请从调用图选择调用点，或打开验证案例。';$('flow-warnings').innerHTML='';$('flow-evidence').innerHTML='';$('bindings').innerHTML='';$('param-focus').innerHTML='<option value="">全部参数</option>';renderBlocks();const b=state.project.blocks.find(b=>b.id===id);$('block-title').textContent=`${b.name} ${b.symbol?'· '+b.symbol:''}`;$('block-description').textContent=b.description||`${statusLabel(b.status)} · ${b.networkCount} 个 Network · ${b.rowCount} 行指令`;$('open-block').disabled=b.status!=='parsed';const graph=await api('calls',{program:state.program,focus:id});if(state.block!==id)return;state.calls=graph.edges;renderCallGraph(graph);renderCallList();}
function renderCallGraph(graph){const focus=graph.nodes.find(n=>n.id===state.block),left=[...new Set(graph.edges.filter(c=>c.target===state.block).map(c=>c.caller))],right=[...new Set(graph.edges.filter(c=>c.caller===state.block).map(c=>c.target))];const col=ids=>`<div class="call-column">${ids.slice(0,12).map(id=>{const b=graph.nodes.find(n=>n.id===id);return `<button class="call-node" data-block="${esc(id)}">${esc(b.name)} ${esc(b.symbol??'')}</button>`;}).join('')||'<span class="small">无直接调用</span>'}${ids.length>12?`<span class="small">另有 ${ids.length-12} 个，见下表</span>`:''}</div>`;$('call-graph').innerHTML=`${col(left)}<div class="arrow">→</div><div class="call-node focus">${esc(focus?.name)}<br>${esc(focus?.symbol??'')}</div><div class="arrow">→</div>${col(right)}`;$('call-graph').querySelectorAll('button').forEach(b=>{if(state.project.blocks.some(x=>x.id===b.dataset.block))b.onclick=safe(()=>selectBlock(b.dataset.block));else b.disabled=true;});if(graph.truncated)$('call-graph').insertAdjacentHTML('beforeend','<p class="small">调用点已截断至前 160 条。</p>');}
function renderCallList(){const rows=state.calls.map(c=>`<tr><td>${esc(c.caller.split('--').at(-1))}</td><td>${esc(c.targetName)} ${esc(c.instance)}</td><td>N${c.network} · 指令 ${c.row}</td><td>${c.parameters.length}</td><td><button data-call="${esc(c.id)}">查看参数流</button></td></tr>`);$('call-list').innerHTML=rows.length?table(['调用者','目标 / 实例','调用位置','参数','操作'],rows):'<div class="empty">该块没有已识别的直接调用关系。</div>';$('call-list').querySelectorAll('button').forEach(b=>b.onclick=safe(()=>selectCall(b.dataset.call)));$('call-select').innerHTML=state.calls.map(c=>`<option value="${esc(c.id)}">${esc(c.caller.split('--').at(-1))} → ${esc(c.targetName)} · N${c.network} / ${c.row}</option>`).join('');}
async function selectCall(id,pointFocus){state.call=id;const call=state.calls.find(c=>c.id===id);if(!call)throw Error('当前调用点不可用');$('call-select').value=id;$('param-focus').innerHTML='<option value="">全部参数</option>'+call.parameters.map(p=>`<option value="${esc(p.name)}">${esc(p.name)} · ${esc(p.direction)}</option>`).join('')+(pointFocus?`<option value="${esc(pointFocus)}">点位 · ${esc(pointFocus)}</option>`:'');$('param-focus').value=pointFocus??(call.parameters.some(p=>p.name==='M_QS')?'M_QS':'');tab('parameters');await renderParameters();}
async function renderParameters(){if(!state.call){$('flow-summary').textContent='请从调用图选择一个调用点。';return;}const graph=await api('parameters',{call:state.call,focus:$('param-focus').value,direction:$('direction').value});if(graph.call.id!==state.call)return;drawFlow(graph);const kinds={'parameter-in':'调用输入绑定','parameter-out':'调用输出绑定','boolean-preparation':'调用前布尔赋值','potential-boolean-dependency':'块内潜在布尔依赖'};const names=new Map(graph.nodes.map(n=>[n.id,n.label]));$('flow-evidence').innerHTML=table(['来源 → 目标','关系','位置',''],graph.edges.map((e,i)=>'<tr><td>'+esc(names.get(e.from))+' → '+esc(names.get(e.to))+'</td><td>'+esc(kinds[e.kind]??e.kind)+'</td><td>'+esc(e.evidence.blockId.split('--').at(-1))+' / N'+e.evidence.network+'</td><td><button data-flow-ref="'+i+'">查看证据</button></td></tr>'));$('flow-evidence').querySelectorAll('button').forEach(b=>b.onclick=safe(()=>showEvidence(graph.edges[Number(b.dataset.flowRef)].evidence)));$('flow-summary').textContent=`${graph.nodes.length} 个节点 · ${graph.edges.length} 条关系 · 被调用块 ${graph.coverage.analyzedCalleeNetworks}/${graph.coverage.totalCalleeNetworks} 个网络支持当前布尔推导${graph.truncated?' · 结果已截断':''}${graph.matched===false?' · 未匹配节点':''}。点击连线查看指令证据。`;const warnings=[...graph.warnings,...graph.coverage.callee.map(d=>d.message)];$('flow-warnings').innerHTML=warnings.length?`<details><summary>${warnings.length} 条范围提示（含本次调用其他参数）</summary><ul>${warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul></details>`:'';$('bindings').innerHTML=table(['参数','方向','类型','原始实参'],graph.call.parameters.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.direction)}</td><td>${esc(p.type)}</td><td>${esc(p.value)}</td></tr>`));}
function drawFlow(graph){const svg=$('flow'),width=1040,nodeWidth=170,positions=new Map(),columns=Array.from({length:5},(_,i)=>graph.nodes.filter(n=>n.column===i)),height=Math.max(270,...columns.map(c=>c.length*65+60));svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.setAttribute('height',height);columns.forEach((nodes,col)=>nodes.forEach((node,i)=>positions.set(node.id,{x:15+col*208,y:(height-nodes.length*65)/2+i*65})));svg.innerHTML='<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#9ab8a9"/></marker></defs>'+graph.edges.map((edge,i)=>{const a=positions.get(edge.from),b=positions.get(edge.to),x1=a.x+nodeWidth,y1=a.y+22,x2=b.x,y2=b.y+22;return `<path class="flow-edge" data-edge="${i}" d="M${x1},${y1} C${x1+35},${y1} ${x2-35},${y2} ${x2},${y2}" marker-end="url(#arrow)"><title>${esc(edge.kind)} · 点击查看证据</title></path>`;}).join('')+graph.nodes.map(node=>{const pos=positions.get(node.id);const text=node.label.length>24?[node.label.slice(0,24),node.label.slice(24,48)]:[node.label];return `<g class="flow-node ${node.parameter?'formal':''}" data-node="${esc(node.id)}" transform="translate(${pos.x},${pos.y})"><title>${esc(node.label)}</title><rect width="${nodeWidth}" height="44"/>${text.map((t,i)=>`<text x="10" y="${text.length===1?26:19+i*15}">${esc(t)}</text>`).join('')}</g>`;}).join('');svg.querySelectorAll('[data-edge]').forEach(el=>el.onclick=safe(()=>showEvidence(graph.edges[Number(el.dataset.edge)].evidence)));svg.querySelectorAll('[data-node]').forEach(el=>el.onclick=safe(async()=>{const n=graph.nodes.find(n=>n.id===el.dataset.node);if(n.parameter){$('param-focus').value=n.parameter;await renderParameters();}}));}
async function showEvidence(evidence){const block=await api('block',{id:evidence.blockId});$('evidence-title').textContent=`${block.name} · Network ${evidence.network??'全部'}${evidence.row?' · 指令 '+evidence.row:''}`;const rows=evidence.network?block.rows.filter(r=>r.network===evidence.network):block.rows.slice(0,500);const code=rows.map(r=>`<span class="code-line ${r.index===evidence.row||r.index===evidence.readRow?'highlight':''}">${String(r.index).padStart(5)}  ${esc(r.label? r.label+': ':'')}${esc(r.command.padEnd(9))}${esc(r.operand)}${r.comment?'  // '+esc(r.comment):''}${r.parameters.map(p=>`\n           ${esc(p.name)} (${esc(p.direction)}) := ${esc(p.value)}`).join('')}</span>`).join('');$('evidence-content').innerHTML=`${!evidence.network?`<details><summary>接口 / 数据结构</summary><pre class="code">${esc(formatStructure(block.interface))}</pre></details>`:''}<pre class="code">${code||'该块没有可显示的指令。'}</pre>${!evidence.network&&block.rows.length>500?'<p class="hint">整块预览显示前 500 行；通过调用点或读写位置可定位后续网络。</p>':''}`;if(!$('evidence').open)$('evidence').showModal();}
function formatStructure(row,depth=0){if(!row)return '';return `${'  '.repeat(depth)}${row.name}: ${row.type}${row.isArray?` [${row.arrayStart.join(',')}..${row.arrayStop.join(',')}]`:''} @ ${row.address} ${row.comment?'// '+row.comment:''}\n`+(row.children??[]).map(c=>formatStructure(c,depth+1)).join('');}
async function searchSymbols(){const result=await api('symbols',{program:state.program,q:$('symbol-search').value});$('symbol-results').innerHTML=`<p class="small">匹配 ${result.total} 条${result.truncated?'，显示前 120 条':''}</p>`+table(['符号','地址','类型','注释',''],result.items.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.operand)}</td><td>${esc(s.type)}</td><td>${esc(s.comment)}</td><td><button data-symbol="${esc(s.name)}">查读写</button></td></tr>`));$('symbol-results').querySelectorAll('button').forEach(b=>b.onclick=safe(()=>searchReferences(b.dataset.symbol)));$('references').innerHTML='';if($('symbol-search').value&&result.total===0)await searchReferences($('symbol-search').value);}
async function searchReferences(query){const result=await api('references',{program:state.program,q:query});$('references').innerHTML=`<p class="small">${esc(query)} / ${esc(result.operand)} · ${result.total} 处${result.truncated?'，显示前 300 处':''}</p>`+table(['程序块','位置','访问','参数 / 指令',''],result.items.map((r,i)=>`<tr><td>${esc(r.blockId.split('--').at(-1))}</td><td>N${r.network} / ${r.row}</td><td>${esc(r.kind)}</td><td>${esc(r.parameter??r.command)}</td><td><button data-ref="${i}">证据</button></td></tr>`));$('references').querySelectorAll('button').forEach(b=>b.onclick=safe(()=>showEvidence(result.items[Number(b.dataset.ref)])));}
function renderCoverage(){const p=state.project;$('coverage-content').innerHTML=`<h3>本版本边界</h3><ul>${p.limitations.map(x=>`<li>${esc(x)}</li>`).join('')}<li>参数流页按完整布尔网络保守推导；点位追踪页另支持分段 L/T、常用算术、比较与条件依赖。跳转路径可达性、间接寻址和完整嵌套调用上下文尚未实现。</li><li>局部参数流限定在一个调用点，避免不同设备的形参和临时位混合。</li></ul><h3>导入诊断 · ${p.diagnostics.length}</h3>${table(['对象','状态','说明'],p.diagnostics.map(d=>`<tr><td>${esc(d.blockId.split('--').at(-1))}</td><td>${esc(d.code)}</td><td>${esc(d.message)}</td></tr>`))}<h3>保存的源码（未合并）</h3>${table(['文件','声明','Network','状态'],p.savedSources.map(s=>`<tr><td>${esc(s.path)}</td><td>${esc(s.declarations.join(', '))}</td><td>${s.networks}</td><td>与离线块未验证一致</td></tr>`))}`;}
$('program').onchange=safe(selectProgram);$('block-search').oninput=renderBlocks;$('call-select').onchange=safe(()=>selectCall($('call-select').value));$('param-focus').onchange=safe(renderParameters);$('direction').onchange=safe(renderParameters);$('open-block').onclick=safe(()=>showEvidence({blockId:state.block}));$('close-evidence').onclick=()=>$('evidence').close();$('symbol-form').onsubmit=safe(async event=>{event.preventDefault();await searchSymbols();});
$('example').onclick=safe(async()=>{const b=state.project.blocks.find(b=>b.programId===state.program&&b.name==='FC231');if(!b)throw Error('当前程序没有 FC231，请选择主 CPU 程序。');await selectBlock(b.id);const c=state.calls.find(c=>c.targetName==='FC156'&&c.parameters.some(p=>p.name==='M_NO'&&p.value==='310'));if(!c)throw Error('当前样本没有匹配的设备 310 调用。');await selectCall(c.id);});
async function loadProject(){state.project=await api('project');const p=state.project;if(p.empty){$('title').textContent='选择 PLC 工程，开始离线分析';$('subtitle').textContent='支持 STEP7 Classic 完整工程文件夹。';$('metrics').innerHTML='';document.querySelector('.workspace').hidden=true;return;}document.querySelector('.workspace').hidden=false;$('folder-path').value=p.sourcePath.replace(/[\\/][^\\/]+$/, '');$('title').textContent=`${p.projectName} · 程序关系与参数流`;$('subtitle').textContent='从工程、调用到参数，每一步都能回到指令证据。';$('stamp').textContent=`快照 ${p.snapshotId.slice(0,12)} · ${new Date(p.importedAt).toLocaleString('zh-CN')}`;const values=[['工程程序',p.programs.length],['块记录',p.blocks.length],['已解析块',p.blocks.filter(b=>b.status==='parsed').length],['符号记录',p.programs.reduce((sum,x)=>sum+x.symbolCount,0)]];$('metrics').innerHTML=values.map(([label,value])=>`<div class="metric"><span>${label}</span><strong>${value.toLocaleString()}</strong></div>`).join('');$('program').innerHTML=p.programs.map(x=>`<option value="${esc(x.id)}">${esc(x.station)} · ${esc(x.cpu)}</option>`).join('');$('program').value=[...p.programs].sort((a,b)=>b.symbolCount-a.symbolCount)[0].id;renderCoverage();await selectProgram();}
await safe(loadProject)();

const post=async(route,body={})=>{const response=await fetch('/api/'+route,{method:'POST',headers:{'Content-Type':'application/json','X-Step7-Local':'1'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error);return data;};
let polling=false;
function importBusy(busy){for(const id of ['browse-folder','inspect-folder','import-project','folder-path','project-file','code-page'])$(id).disabled=busy;$('import-progress').hidden=!busy;}
async function inspectFolder(){const result=await post('inspect-folder',{folder:$('folder-path').value});$('project-candidates').hidden=result.projects.length===0;$('project-file').innerHTML=result.projects.map(p=>'<option value="'+esc(p.path)+'">'+esc(p.path)+'</option>').join('');$('import-message').textContent=result.projects.length?'识别到 '+result.projects.length+' 个工程，请选择入口后点击“导入并打开”。':'没有找到 .S7P 文件，请选择工程所在文件夹（最多查找两层子目录）。';}
async function pollImport(){if(polling)return;polling=true;try{const job=await api('import-status');if(job.status==='idle')return;importBusy(job.status==='running');$('import-message').textContent=job.message;if(job.status==='running'){setTimeout(()=>safe(pollImport)(),1000);}else if(job.status==='complete'){await loadProject();$('project-candidates').hidden=true;}else if(job.status==='failed'){$('error').textContent='导入未完成：'+job.message;$('error').hidden=false;}}finally{polling=false;}}
$('browse-folder').onclick=safe(async()=>{$('browse-folder').disabled=true;$('import-message').textContent='请在 Windows 文件夹选择窗口中选择工程，或取消后直接输入路径。';try{const result=await post('select-folder');if(result.cancelled){$('import-message').textContent='已取消选择。';return;}$('folder-path').value=result.path;await inspectFolder();}finally{$('browse-folder').disabled=false;}});
$('folder-form').onsubmit=safe(async event=>{event.preventDefault();await inspectFolder();});
$('folder-path').oninput=()=>{$('project-candidates').hidden=true;};
$('import-project').onclick=safe(async()=>{importBusy(true);try{const job=await post('import',{projectFile:$('project-file').value,codePage:Number($('code-page').value)});$('import-message').textContent=job.message;await pollImport();}catch(error){importBusy(false);throw error;}});
const activeJob=await api('import-status');if(activeJob.status==='running')await safe(pollImport)();

$('point-form').onsubmit=safe(async event=>{
  event.preventDefault();disposeFlowExplorer();const program=state.program,snapshot=state.project.snapshotId;
  $('point-submit').disabled=true;$('point-results').innerHTML='<p class="empty">正在查找直接读写与参数路径…</p>';
  try{
    const result=await api('point',{program,q:$('point-query').value});
    if(program!==state.program||snapshot!==state.project.snapshotId)return;
    if(result.ambiguous){$('point-results').innerHTML='<p class="notice">此符号对应多个点位，请输入具体地址：</p>'+table(['符号','地址'],result.candidates.map(s=>'<tr><td>'+esc(s.name)+'</td><td>'+esc(s.operand)+'</td></tr>'));return;}
    const blockName=id=>id.split('--').at(-1);
    const flowText=graph=>Array.from({length:5},(_,column)=>graph.nodes.filter(n=>n.column===column).map(n=>n.label).join(' / ')).filter(Boolean).join(' → ');
    $('point-results').innerHTML='<h3>'+esc(result.operand)+(result.symbols.length?' · '+esc(result.symbols.map(s=>s.name).join(' / ')):'')+'</h3><p>找到 <strong>'+result.directBlocks.length+' 个直接使用块</strong>、'+result.referenceTotal+' 处读写引用，以及 <strong>'+result.totalCalls+' 个相关功能块调用点</strong>。'+(result.truncated?'结果有截断，请缩小范围。':'')+'</p><h3>哪些程序块直接使用</h3>'+
      (result.directBlocks.length?table(['程序块','说明','读 / 写引用'],result.directBlocks.map(b=>'<tr><td>'+esc(b.name)+'</td><td>'+esc(b.symbol||b.description)+'</td><td>'+b.reads+' / '+b.writes+'</td></tr>')):'<p class="empty">没有找到已解析的直接读写；请检查所选 CPU 和地址。该结果不能排除间接访问或受保护块的使用。</p>')+
      pointFlowMarkup(result.flow)+'<h3>相关功能块调用与流向</h3>'+(result.relatedCalls.length?result.relatedCalls.map((item,i)=>'<section class="point-call"><h4>'+esc(blockName(item.call.caller))+' → '+esc(item.call.targetName)+(item.call.instance?' · '+esc(item.call.instance):'')+' <span class="small">Network '+item.call.network+' / 指令 '+item.call.row+'</span></h4><p class="point-path">'+(item.graph.nodes.length?esc(flowText(item.graph)):'此调用与点位的直接使用或上方数据流有关；可查看调用指令确认参数。')+'</p><p class="small">'+(item.graph.nodes.length?'已还原 '+item.graph.nodes.length+' 个节点、'+item.graph.edges.length+' 条关系。被调用块布尔网络覆盖 '+item.graph.coverage.analyzedCalleeNetworks+'/'+item.graph.coverage.totalCalleeNetworks+'。':'数值路径见上方点位流程图；该调用的局部布尔图可能没有匹配节点。')+'</p><button data-point-call="'+i+'">'+(item.graph.nodes.length?'展开参数图与证据':'查看调用位置')+'</button></section>').join(''):'<p class="empty">尚未连接到可还原的功能块调用路径。下表保留已找到的直接读写位置。</p>')+
      '<h3>直接读写的指令证据</h3>'+table(['程序块','位置','访问','参数 / 指令',''],result.references.map((r,i)=>'<tr><td>'+esc(blockName(r.blockId))+'</td><td>N'+r.network+' / '+r.row+'</td><td>'+esc({read:'读取',write:'写入','read-write':'读写'}[r.kind])+'</td><td>'+esc(r.parameter??r.command)+'</td><td><button data-point-ref="'+i+'">查看证据</button></td></tr>'))+
      '<p class="small">当前程序：'+result.coverage.parsedBlocks+' 个已解析块，'+result.coverage.protectedBlocks+' 个保护块，'+result.coverage.unavailableBlocks+' 个不可查询指令的块记录。</p><ul class="small">'+result.warnings.map(w=>'<li>'+esc(w)+'</li>').join('')+'</ul>';
    drawPointFlow(result.flow);
    $('point-results').querySelectorAll('[data-point-ref]').forEach(button=>button.onclick=safe(()=>showEvidence(result.references[Number(button.dataset.pointRef)])));
    $('point-results').querySelectorAll('[data-point-call]').forEach(button=>button.onclick=safe(async()=>{
      const item=result.relatedCalls[Number(button.dataset.pointCall)];
      if(!item.graph.nodes.length){await showEvidence({blockId:item.call.caller,network:item.call.network,row:item.call.row});return;}
      await selectBlock(item.call.caller);
      if(!state.calls.some(c=>c.id===item.call.id)){state.calls.push(item.call);renderCallList();}
      $('direction').value='both';await selectCall(item.call.id,result.operand);
    }));
  }catch(error){$('point-results').innerHTML='<p class="empty">本次追踪未完成，请检查点位输入。</p>';throw error;}
  finally{$('point-submit').disabled=false;}
});

function pointFlowMarkup(flow){
  const names=new Map(flow.nodes.map(n=>[n.id,n.label]));
  const unique=values=>[...new Set(values)];
  const source=unique(flow.edges.filter(e=>e.to===flow.focus).map(e=>names.get(e.from)));
  const valueTargets=unique(flow.edges.filter(e=>e.from===flow.focus&&['data-transfer','parameter-in','parameter-out','argument-preparation'].includes(e.kind)).map(e=>names.get(e.to)));
  const conditionTargets=unique(flow.edges.filter(e=>e.from===flow.focus&&!['data-transfer','parameter-in','parameter-out','argument-preparation'].includes(e.kind)).map(e=>names.get(e.to)));
  const kinds={'data-transfer':'数值 / 运算结果传递','control-dependency':'逻辑条件影响','timer-dependency':'定时器条件影响','parameter-in':'输入参数绑定','parameter-out':'输出参数绑定','argument-preparation':'调用前参数准备'};
  return '<h3>点位的来源与去向</h3><div class="point-overview"><p><strong>直接来源：</strong>'+esc(source.join('；')||'当前分析未还原写入来源，不能据此判断没有来源。')+'</p><p><strong>数值 / 参数去向：</strong>'+esc(valueTargets.join('；')||'未还原直接数值去向。')+'</p><p><strong>还参与条件：</strong>'+esc(conditionTargets.join('；')||'未还原条件影响。')+'</p></div>'+flowExplorerMarkup()+'<p class="small">'+flow.nodes.length+' 个节点 · '+flow.edges.length+' 条证据关系 · 最多上下游各 '+flow.limits.maxDepth+' 层'+(flow.truncated?' · 达到显示上限，边界已标出，可继续输入边界点位追踪。':'')+'</p><details><summary>流程图的全部关系与证据</summary>'+table(['来源 → 去向','关系','位置',''],flow.edges.map((e,i)=>'<tr><td>'+esc(names.get(e.from))+' → '+esc(names.get(e.to))+'</td><td>'+esc(kinds[e.kind]??e.kind)+'</td><td>'+esc(e.evidence.blockId.split('--').at(-1))+' / N'+e.evidence.network+' / '+e.evidence.row+'</td><td><button data-memory-ref="'+i+'">查看证据</button></td></tr>'))+'</details>';
}
function drawPointFlow(flow){
  mountFlowExplorer(flow,safe(showEvidence));
  $('point-results').querySelectorAll('[data-memory-ref]').forEach(el=>el.onclick=safe(()=>showEvidence(flow.edges[Number(el.dataset.memoryRef)].evidence)));
}